schema_version = "1.0.0"
id = "gridarray"
version = "1.0.0"
name = "GridArray"
tagline = "Create grid-like arrays along X, Y, and Z axes with a user-friendly interface"
maintainer = "KSYN <ksyn@example.com>"
type = "add-on"

tags = ["Modeling", "Object", "Mesh"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
]